### ISSUE TITLE
Add support for .NET standard TimeSpan format strings

### ISSUE THREAD

**Issue by stevdompl** [jkroso/parse-duration#29]
Hi,

is it possible to add support for .NET TimeSpan strings? 
I have to add moment.js library as a dependency (besides yours) just for parsing this format.

More details: https://docs.microsoft.com/en-US/dotnet/standard/base-types/standard-timespan-format-strings

**Comment by dy** [comment]
I think you're looking more for generic duration parser, this one targets only human-readable duration, it doesn't set goal to parse every known duration format.
I believe the correct way to address your problem is to combine multiple tiny packages for parsing formats you need, or else including moment.js indeed, if that task isn't sensitive to size/perf.
